import type { Metadata } from 'next'
import { motion } from 'framer-motion'
import Link from 'next/link'
import { Shield, ArrowLeft, FileText, Lock, Eye, Zap } from 'lucide-react'

export const metadata: Metadata = {
  title: 'Privacy Policy — OptimeCore Intelligence Platform',
  description: 'Learn about how OptimeCore collects, uses, and protects your industrial data.',
}

export default function PrivacyPolicy() {
  return (
    <main className="min-h-screen bg-black font-['Cinzel'] text-[#F2F1F0] selection:bg-[#3F7373]/30">
      {/* Background Decor */}
      <div className="fixed inset-0 pointer-events-none">
        <div className="absolute w-[800px] h-[800px] rounded-full blur-[180px] opacity-[0.05] bg-[#3F7373] -top-64 -left-64" />
        <div className="absolute w-[600px] h-[600px] rounded-full blur-[150px] opacity-[0.04] bg-[#768C45] bottom-0 right-0" />
        <div
          className="absolute inset-0 opacity-[0.02]"
          style={{
            backgroundImage: `linear-gradient(rgba(255,255,255,0.05) 1px, transparent 1px), linear-gradient(90deg, rgba(255,255,255,0.05) 1px, transparent 1px)`,
            backgroundSize: '40px 40px',
          }}
        />
      </div>

      <div className="relative z-10 max-w-4xl mx-auto px-6 pt-32 pb-24">
        {/* Back Button */}
        <Link
          href="/"
          className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-white/5 border border-white/10 text-[10px] font-bold tracking-[0.3em] uppercase text-[#A8BDBF]/60 hover:text-[#F2F1F0] transition-colors mb-12"
        >
          <ArrowLeft className="w-3 h-3" /> Back to Home
        </Link>

        {/* Header */}
        <div className="mb-16">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-[#3F7373]/10 border border-[#3F7373]/30 text-[9px] font-black tracking-[0.4em] uppercase text-[#3F7373] mb-6">
            <Lock className="w-3 h-3" />
            <span>sys.security.protocol</span>
          </div>
          <h1 className="text-5xl md:text-7xl font-black uppercase tracking-tighter leading-none mb-6">
            Privacy <span className="text-transparent bg-clip-text bg-gradient-to-r from-[#3F7373] to-[#A8BDBF]">Policy</span>
          </h1>
          <p className="text-[#A8BDBF]/40 text-sm font-sans tracking-widest uppercase">
            Last Updated: March 11, 2026
          </p>
        </div>

        {/* Content Section */}
        <div className="space-y-12 font-sans text-[#A8BDBF]/80 leading-relaxed max-w-3xl">
          <section>
            <h2 className="text-xl font-black text-[#F2F1F0] uppercase tracking-tight mb-4 flex items-center gap-3 font-['Cinzel']">
              <span className="w-1.5 h-6 bg-[#3F7373]" /> 01. Overview
            </h2>
            <p>
              At OptimeCore, we recognize the critical importance of data privacy in industrial environments. This Privacy Policy outlines how our platform collects, uses, and safeguards the information generated by your factory operations and personnel.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-black text-[#F2F1F0] uppercase tracking-tight mb-4 flex items-center gap-3 font-['Cinzel']">
              <span className="w-1.5 h-6 bg-[#768C45]" /> 02. Data Collection
            </h2>
            <p className="mb-4">
              Our platform processes two primary types of data:
            </p>
            <ul className="space-y-4">
              <li className="flex gap-4 p-4 border border-white/5 bg-white/[0.02]">
                <div className="w-10 h-10 shrink-0 rounded-lg bg-[#3F7373]/10 border border-[#3F7373]/20 flex items-center justify-center">
                  <Zap className="w-5 h-5 text-[#3F7373]" />
                </div>
                <div>
                  <h3 className="text-sm font-bold text-[#F2F1F0] uppercase tracking-wide mb-1">Operational Telemetry</h3>
                  <p className="text-sm">Machine cycles, sensor logs, energy consumption, and production throughput data transmitted via industrial protocols (OPC-UA, MQTT).</p>
                </div>
              </li>
              <li className="flex gap-4 p-4 border border-white/5 bg-white/[0.02]">
                <div className="w-10 h-10 shrink-0 rounded-lg bg-[#768C45]/10 border border-[#768C45]/20 flex items-center justify-center">
                  <Eye className="w-5 h-5 text-[#768C45]" />
                </div>
                <div>
                  <h3 className="text-sm font-bold text-[#F2F1F0] uppercase tracking-wide mb-1">User Metadata</h3>
                  <p className="text-sm">Account credentials, access logs, and system preferences for authorized factory personnel.</p>
                </div>
              </li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-black text-[#F2F1F0] uppercase tracking-tight mb-4 flex items-center gap-3 font-['Cinzel']">
              <span className="w-1.5 h-6 bg-[#A8BDBF]" /> 03. Data Sovereignty
            </h2>
            <p>
              OptimeCore adheres to strict data sovereignty principles. Your operational data remains your property. We process this data solely to provide analytics, predictive maintenance alerts, and efficiency insights. We do not sell or trade industrial telemetry to third parties.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-black text-[#F2F1F0] uppercase tracking-tight mb-4 flex items-center gap-3 font-['Cinzel']">
              <span className="w-1.5 h-6 bg-[#C5D7D9]" /> 04. Security Protocols
            </h2>
            <p>
              All data transmitted to the OptimeCore Intelligence Platform is encrypted using AES-256 at rest and TLS 1.3 in transit. We conduct regular SOC 2 Type II audits and penetration testing to ensure the integrity of your factory's digital perimeter.
            </p>
          </section>

          <section className="pt-8 border-t border-white/10">
            <h3 className="text-sm font-bold text-[#F2F1F0] uppercase tracking-[0.2em] mb-4 font-['Cinzel']">Contact Security Office</h3>
            <p className="text-sm mb-6">
              For inquiries regarding data protection or to request a security audit report:
            </p>
            <a href="mailto:security@optimecore.com" className="inline-flex items-center gap-2 text-[#3F7373] font-bold text-sm border-b border-[#3F7373]/30 hover:border-[#3F7373] transition-all pb-1">
              security@optimecore.com <ArrowLeft className="w-3 h-3 rotate-[135deg]" />
            </a>
          </section>
        </div>
      </div>

      {/* Footer Minimal */}
      <footer className="border-t border-white/5 py-12 px-6">
        <div className="max-w-4xl mx-auto flex flex-col md:flex-row justify-between items-center gap-6">
          <p className="text-[9px] font-bold tracking-[0.3em] text-[#A8BDBF]/20 uppercase">
            © 2026 OptimeCore Intelligence Platform
          </p>
          <div className="flex gap-8">
            <Link href="/terms-and-conditions" className="text-[9px] font-bold tracking-[0.3em] text-[#A8BDBF]/40 hover:text-[#F2F1F0] uppercase transition-colors">
              Terms of Use
            </Link>
            <Link href="/contact" className="text-[9px] font-bold tracking-[0.3em] text-[#A8BDBF]/40 hover:text-[#F2F1F0] uppercase transition-colors">
              Contact
            </Link>
          </div>
        </div>
      </footer>
    </main>
  )
}
